lib/code_camp_web/router.ex
defmodule CodeCampWeb.Router do
  use CodeCampWeb, :router
  use Kaffy.Routes #, scope: "/admin", pipe_through: [:some_plug, :authenticate]

  import CodeCampWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {CodeCampWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CodeCampWeb do
    pipe_through :browser

    live "/", PageLive, :index
    live "/profesores", TeacherLive, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", CodeCampWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: CodeCampWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", CodeCampWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated, :put_session_layout]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", CodeCampWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", CodeCampWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
    get "/aboutus", AboutController, :index
  end

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end
end

lib/code_camp_web/controllers/user_registration_controller.ex
defmodule CodeCampWeb.UserRegistrationController do
  use CodeCampWeb, :controller

  alias CodeCamp.Accounts
  alias CodeCamp.Accounts.User
  alias CodeCampWeb.UserAuth

  def new(conn, _params) do
    changeset = Accounts.change_user_registration(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        {:ok, _} =
          Accounts.deliver_user_confirmation_instructions(
            user,
            &Routes.user_confirmation_url(conn, :confirm, &1)
          )

        conn
        |> put_flash(:info, "Usuario creado exitosamente.")
        |> UserAuth.log_in_user(user)

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/code_camp_web/views/user_registration_view.ex
defmodule CodeCampWeb.UserRegistrationView do
  use CodeCampWeb, :view
end

lib/code_camp_web/templates/user_registration/new.html.eex
<h5 class="px-5 pb-2 text-lg leading-normal text-center">Registrate</h5>
<%= form_for @changeset, Routes.user_registration_path(@conn, :create), fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <small>¡Vaya, algo ha salido mal! Por favor revisa los errores a continuación.</small>
    </div>
  <% end %>

  <div class="my-4">
    <%= label f, :correo, class: "form-label" %>
    <%= text_input f, :email, required: true, class: "form-input" %>
    <%= error_tag f, :email %>
  </div>

  <div class="mb-4">
    <%= label f, :contraseña, class: "form-label" %>
    <%= password_input f, :password, required: true, class: "form-input" %>
    <%= error_tag f, :password %>
  </div>

  <div class="mt-6">
    <%= submit "Registrarme", class: "text-gray-800 bg-la-green btn btn-sm btn-link w-full" %>
  </div>
<% end %>

<div class="my-3 text-center">
  <%= link "Olvidé mi contraseña", to: Routes.user_reset_password_path(@conn, :new), class: "text-gray-800 btn btn-link btn-sm" %>
  <div class="inline-flex flex-nowrap w-full justify-around place-items-center">
    <hr class="w-2/5 border-t-4 border-solid border-gray-100">
      <span>o</span>
    <hr class="w-2/5 border-t-4 border-solid border-gray-100">
  </div>
  <small class="mt-3 text-gray-600">¿Ya tienes una cuenta?</small>
  <%= link "Inicia sesión", to: Routes.user_session_path(@conn, :new), class: "text-gray-800 btn btn-link btn-sm" %>
</div>